import {
  LucideTableOfContents,
  LucideGlobe,
  LucideUser,
  LucideLock,
  LucideMonitor,
  LucideTriangleAlert,
  LucideX,
  LucidePlus,
  LucideCircleX,
  LucidePencil,
  LucideTrash,
  LucideEllipsis,
  LucideSettings,
  LucideTv,
  LucideClapperboard,
  LucideMonitorPlay,
  LucidePlay,
  LucideSearch,
} from "@lucide/angular";

export const LUCIDE_ICONS = [
  LucideTableOfContents,
  LucideGlobe,
  LucideUser,
  LucideLock,
  LucideMonitor,
  LucideTriangleAlert,
  LucideX,
  LucidePlus,
  LucideCircleX,
  LucidePencil,
  LucideTrash,
  LucideEllipsis,
  LucideSettings,
  LucideTv,
  LucideClapperboard,
  LucideMonitorPlay,
  LucidePlay,
  LucideSearch,
] as const;
